# -*- coding: utf-8 -*-
"""APP_GRADIO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GkiH8i3AVKyTFeShv8NKUlqeYqJDxw6z
"""

!pip install gradio joblib groq scikit-learn sentence-transformers

import joblib
import gradio as gr
import os
from groq import Groq
from sentence_transformers import SentenceTransformer

# Load saved models
tfidf = joblib.load("/content/tfidf_vectorizer.pkl")
tfidf_model = joblib.load("/content/balanced_svm_tfidf.pkl")

bert_svm = joblib.load("/content/bert_balanced_svm.pkl")

with open("/content/bert_model_name.txt", "r") as f:
    bert_model_name = f.read().strip()

bert_model = SentenceTransformer(bert_model_name)

GROQ_API_KEY = "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"

client = Groq(api_key=GROQ_API_KEY)

def explain_with_llm(text, label, confidence):
    prompt = f"""
Explain why the following SMS is classified as {label} using simple reasoning.

SMS: {text}
Prediction: {label}
Confidence: {confidence:.2f}

Keep the explanation short and clear.
"""

    response = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        messages=[
            {"role": "user", "content": prompt}
        ]
    )

    return response.choices[0].message.content

def predict_sms(sms_text):
    if sms_text.strip() == "":
        return "Please enter an SMS message.", "", ""

    # BERT embedding
    sms_embedding = bert_model.encode([sms_text])

    # Prediction
    prediction = bert_svm.predict(sms_embedding)[0]
    probabilities = bert_svm.predict_proba(sms_embedding)[0]

    label = "Spam" if prediction == 1 else "Ham"
    confidence = probabilities[prediction]

    # LLM explanation
    explanation = explain_with_llm(sms_text, label, confidence)

    return label, f"{confidence:.4f}", explanation

app = gr.Interface(
    fn=predict_sms,
    inputs=gr.Textbox(
        lines=5,
        placeholder="Enter SMS message here...",
        label="SMS Message"
    ),
    outputs=[
        gr.Textbox(label="Prediction"),
        gr.Textbox(label="Confidence"),
        gr.Textbox(label="Explanation",
                   lines=10,
                   max_lines=20
        )
    ],
    title="SMS Spam Detection System",
    description="Enter an SMS message to classify it as Spam or Ham with confidence and LLM explanation."
)

app.launch(share=True)

